module.exports = {
    SET_LOADING:'SET_LOADING',
    SET_THEME:'SET_THEME',
    UPDATE_LOGIN_STATES:'UPDATE_LOGIN_STATES',
    CHANGE_BASE_THEME:'CHANGE_BASE_THEME',
    CHANGE_COLOR_THEME:'CHANGE_COLOR_THEME',
    GET_CURRIENCIES:'GET_CURRIENCIES',
    GET_CURRIENCIES_ACTION:'GET_CURRIENCIES_ACTION',
    ADD_TO_FAVS:'ADD_TO_FAVS',
    UPDATE_BASE:'UPDATE_BASE',
    UPDATE_EXCHANGE:'UPDATE_EXCHANGE',
    REVERSE_CURRENCIES:'REVERSE_CURRENCIES'


    
}